// Sample data for 30 mineral collectors worldwide
const mineralCollectors = [
    {
        id: 1,
        name: "Dr. Sarah Chen",
        location: "San Francisco, CA",
        coordinates: [-122.4194, 37.7749],
        country: "United States",
        specialization: "Quartz Varieties",
        totalMinerals: 45,
        rareFinds: 8,
        yearsCollecting: 12,
        favoriteMineral: "Amethyst",
        bio: "Geologist specializing in silicon dioxide crystal formations",
        profileImage: "https://images.unsplash.com/photo-1494790108755-2616b612b567?w=150&h=150&fit=crop&crop=face",
        minerals: ["Amethyst", "Citrine", "Rose Quartz", "Smoky Quartz", "Clear Quartz", "Ametrine", "Phantom Quartz", "Rutilated Quartz"]
    },
    {
        id: 2,
        name: "Hans Mueller",
        location: "Munich, Germany",
        coordinates: [11.5820, 48.1351],
        country: "Germany",
        specialization: "Alpine Minerals",
        totalMinerals: 67,
        rareFinds: 15,
        yearsCollecting: 25,
        favoriteMineral: "Epidote",
        bio: "Alpine mineral specialist with focus on European localities",
        profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
        minerals: ["Epidote", "Actinolite", "Albite", "Chlorite", "Titanite", "Adularia", "Hematite", "Pyrite", "Calcite"]
    },
    {
        id: 3,
        name: "Maria Santos",
        location: "Rio de Janeiro, Brazil",
        coordinates: [-43.1729, -22.9068],
        country: "Brazil",
        specialization: "Gemstones",
        totalMinerals: 89,
        rareFinds: 23,
        yearsCollecting: 18,
        favoriteMineral: "Tourmaline",
        bio: "Gemstone dealer and collector from the famous Minas Gerais region",
        profileImage: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face",
        minerals: ["Tourmaline", "Topaz", "Beryl", "Aquamarine", "Morganite", "Heliodor", "Emerald", "Chrysoberyl", "Garnet", "Spodumene"]
    },
    {
        id: 4,
        name: "Yuki Tanaka",
        location: "Tokyo, Japan",
        coordinates: [139.6917, 35.6895],
        country: "Japan",
        specialization: "Zeolites",
        totalMinerals: 34,
        rareFinds: 7,
        yearsCollecting: 8,
        favoriteMineral: "Stilbite",
        bio: "Zeolite enthusiast focusing on Japanese volcanic mineral localities",
        profileImage: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=150&h=150&fit=crop&crop=face",
        minerals: ["Stilbite", "Heulandite", "Chabazite", "Mordenite", "Analcime", "Natrolite", "Laumontite", "Clinoptilolite"]
    },
    {
        id: 5,
        name: "Pierre Dubois",
        location: "Lyon, France",
        coordinates: [4.8357, 45.7640],
        country: "France",
        specialization: "Fluorite",
        totalMinerals: 52,
        rareFinds: 11,
        yearsCollecting: 15,
        favoriteMineral: "Purple Fluorite",
        bio: "French fluorite specialist with extensive European collection",
        profileImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
        minerals: ["Purple Fluorite", "Green Fluorite", "Blue Fluorite", "Yellow Fluorite", "Clear Fluorite", "Pink Fluorite", "Rainbow Fluorite"]
    },
    {
        id: 6,
        name: "Ahmed Hassan",
        location: "Cairo, Egypt",
        coordinates: [31.2357, 30.0444],
        country: "Egypt",
        specialization: "Desert Minerals",
        totalMinerals: 38,
        rareFinds: 9,
        yearsCollecting: 10,
        favoriteMineral: "Desert Rose",
        bio: "Desert mineral collector specializing in Saharan specimens",
        profileImage: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face",
        minerals: ["Desert Rose", "Selenite", "Gypsum", "Barite", "Celestite", "Halite", "Anhydrite", "Dolomite"]
    },
    {
        id: 7,
        name: "Emma Thompson",
        location: "London, UK",
        coordinates: [-0.1276, 51.5074],
        country: "United Kingdom",
        specialization: "British Minerals",
        totalMinerals: 43,
        rareFinds: 6,
        yearsCollecting: 14,
        favoriteMineral: "Fluorite",
        bio: "British mineral enthusiast focusing on UK mining heritage",
        profileImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
        minerals: ["Fluorite", "Galena", "Sphalerite", "Barite", "Calcite", "Quartz", "Pyrite", "Chalcopyrite", "Witherite"]
    },
    {
        id: 8,
        name: "Raj Patel",
        location: "Mumbai, India",
        coordinates: [72.8777, 19.0760],
        country: "India",
        specialization: "Zeolites & Basalt Minerals",
        totalMinerals: 56,
        rareFinds: 12,
        yearsCollecting: 16,
        favoriteMineral: "Apophyllite",
        bio: "Deccan Trap specialist focusing on zeolite formations",
        profileImage: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
        minerals: ["Apophyllite", "Stilbite", "Heulandite", "Cavansite", "Chalcedony", "Agate", "Prehnite", "Calcite", "Gyrolite"]
    },
    {
        id: 9,
        name: "Lars Andersen",
        location: "Oslo, Norway",
        coordinates: [10.7522, 59.9139],
        country: "Norway",
        specialization: "Scandinavian Minerals",
        totalMinerals: 41,
        rareFinds: 8,
        yearsCollecting: 11,
        favoriteMineral: "Thulite",
        bio: "Nordic mineral collector specializing in Scandinavian localities",
        profileImage: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face",
        minerals: ["Thulite", "Amazonite", "Orthoclase", "Epidote", "Actinolite", "Hornblende", "Labradorite", "Moonstone"]
    },
    {
        id: 10,
        name: "Sofia Petrov",
        location: "Moscow, Russia",
        coordinates: [37.6176, 55.7558],
        country: "Russia",
        specialization: "Ural Mountains Minerals",
        totalMinerals: 73,
        rareFinds: 18,
        yearsCollecting: 22,
        favoriteMineral: "Demantoid Garnet",
        bio: "Ural Mountains specialist with rare Russian mineral specimens",
        profileImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
        minerals: ["Demantoid Garnet", "Alexandrite", "Emerald", "Topaz", "Malachite", "Azurite", "Charoite", "Phenakite", "Chrysoberyl"]
    },
    {
        id: 11,
        name: "Carlos Rodriguez",
        location: "Mexico City, Mexico",
        coordinates: [-99.1332, 19.4326],
        country: "Mexico",
        specialization: "Silver Minerals",
        totalMinerals: 48,
        rareFinds: 10,
        yearsCollecting: 13,
        favoriteMineral: "Native Silver",
        bio: "Mexican silver mineral specialist from historic mining regions",
        profileImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
        minerals: ["Native Silver", "Acanthite", "Pyrargyrite", "Proustite", "Stephanite", "Galena", "Sphalerite", "Calcite", "Barite"]
    },
    {
        id: 12,
        name: "Isabella Rossi",
        location: "Rome, Italy",
        coordinates: [12.4964, 41.9028],
        country: "Italy",
        specialization: "Vesuvius Minerals",
        totalMinerals: 39,
        rareFinds: 7,
        yearsCollecting: 9,
        favoriteMineral: "Vesuvianite",
        bio: "Italian volcanic mineral collector focusing on Vesuvius specimens",
        profileImage: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=150&h=150&fit=crop&crop=face",
        minerals: ["Vesuvianite", "Leucite", "Nepheline", "Sodalite", "Haüyne", "Nosean", "Sanidine", "Pyroxene", "Olivine"]
    },
    {
        id: 13,
        name: "Chen Wei",
        location: "Beijing, China",
        coordinates: [116.4074, 39.9042],
        country: "China",
        specialization: "Chinese Minerals",
        totalMinerals: 62,
        rareFinds: 14,
        yearsCollecting: 17,
        favoriteMineral: "Realgar",
        bio: "Chinese mineral collector specializing in classic Chinese localities",
        profileImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
        minerals: ["Realgar", "Orpiment", "Cinnabar", "Stibnite", "Marcasite", "Pyrite", "Quartz", "Fluorite", "Calcite", "Galena"]
    },
    {
        id: 14,
        name: "David Mitchell",
        location: "Sydney, Australia",
        coordinates: [151.2093, -33.8688],
        country: "Australia",
        specialization: "Opals",
        totalMinerals: 55,
        rareFinds: 13,
        yearsCollecting: 19,
        favoriteMineral: "Black Opal",
        bio: "Australian opal specialist from the famous opal fields",
        profileImage: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150&h=150&fit=crop&crop=face",
        minerals: ["Black Opal", "White Opal", "Boulder Opal", "Crystal Opal", "Fire Opal", "Water Opal", "Common Opal", "Precious Opal"]
    },
    {
        id: 15,
        name: "Anna Kowalski",
        location: "Warsaw, Poland",
        coordinates: [21.0122, 52.2297],
        country: "Poland",
        specialization: "Amber & Sulfides",
        totalMinerals: 44,
        rareFinds: 9,
        yearsCollecting: 12,
        favoriteMineral: "Baltic Amber",
        bio: "Polish collector specializing in Baltic amber and sulfide minerals",
        profileImage: "https://images.unsplash.com/photo-1574701148212-8518049c7b0b?w=150&h=150&fit=crop&crop=face",
        minerals: ["Baltic Amber", "Pyrite", "Marcasite", "Galena", "Sphalerite", "Chalcopyrite", "Bornite", "Covellite", "Chalcocite"]
    },
    {
        id: 16,
        name: "João Silva",
        location: "São Paulo, Brazil",
        coordinates: [-46.6333, -23.5505],
        country: "Brazil",
        specialization: "Pegmatite Minerals",
        totalMinerals: 71,
        rareFinds: 16,
        yearsCollecting: 21,
        favoriteMineral: "Kunzite",
        bio: "Brazilian pegmatite specialist from Minas Gerais region",
        profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
        minerals: ["Kunzite", "Hiddenite", "Spodumene", "Lepidolite", "Tourmaline", "Beryl", "Topaz", "Quartz", "Feldspar", "Mica"]
    },
    {
        id: 17,
        name: "Fatima Al-Zahra",
        location: "Dubai, UAE",
        coordinates: [55.2708, 25.2048],
        country: "UAE",
        specialization: "Rare Earth Minerals",
        totalMinerals: 33,
        rareFinds: 11,
        yearsCollecting: 7,
        favoriteMineral: "Gadolinite",
        bio: "Rare earth element mineral collector with global focus",
        profileImage: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face",
        minerals: ["Gadolinite", "Xenotime", "Monazite", "Bastnäsite", "Cerite", "Allanite", "Euxenite", "Samarskite"]
    },
    {
        id: 18,
        name: "Robert Johnson",
        location: "Toronto, Canada",
        coordinates: [-79.3832, 43.6532],
        country: "Canada",
        specialization: "Canadian Shield Minerals",
        totalMinerals: 58,
        rareFinds: 12,
        yearsCollecting: 16,
        favoriteMineral: "Sodalite",
        bio: "Canadian Shield mineral collector focusing on Precambrian geology",
        profileImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
        minerals: ["Sodalite", "Nepheline", "Cancrinite", "Labradorite", "Anorthite", "Bytownite", "Hornblende", "Biotite", "Magnetite"]
    },
    {
        id: 19,
        name: "Ingrid Larsson",
        location: "Stockholm, Sweden",
        coordinates: [18.0686, 59.3293],
        country: "Sweden",
        specialization: "Iron Minerals",
        totalMinerals: 46,
        rareFinds: 8,
        yearsCollecting: 14,
        favoriteMineral: "Magnetite",
        bio: "Swedish iron mineral specialist from historic mining regions",
        profileImage: "https://images.unsplash.com/photo-1596815064285-45ed8a9c0463?w=150&h=150&fit=crop&crop=face",
        minerals: ["Magnetite", "Hematite", "Limonite", "Goethite", "Pyrite", "Pyrrhotite", "Marcasite", "Siderite", "Chalcopyrite"]
    },
    {
        id: 20,
        name: "Miguel Fernandez",
        location: "Madrid, Spain",
        coordinates: [-3.7038, 40.4168],
        country: "Spain",
        specialization: "Spanish Sulfides",
        totalMinerals: 51,
        rareFinds: 10,
        yearsCollecting: 15,
        favoriteMineral: "Cinnabar",
        bio: "Spanish sulfide mineral collector from Iberian Peninsula localities",
        profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
        minerals: ["Cinnabar", "Pyrite", "Galena", "Sphalerite", "Chalcopyrite", "Tetrahedrite", "Enargite", "Bournonite", "Jamesonite"]
    },
    {
        id: 21,
        name: "Kenji Nakamura",
        location: "Kyoto, Japan",
        coordinates: [135.7681, 35.0116],
        country: "Japan",
        specialization: "Japanese Classics",
        totalMinerals: 37,
        rareFinds: 9,
        yearsCollecting: 11,
        favoriteMineral: "Epidote",
        bio: "Traditional Japanese mineral collector focusing on classic localities",
        profileImage: "https://images.unsplash.com/photo-1566492031773-4f4e44671d66?w=150&h=150&fit=crop&crop=face",
        minerals: ["Epidote", "Quartz", "Actinolite", "Albite", "Chlorite", "Prehnite", "Pumpellyite", "Calcite", "Pyrite"]
    },
    {
        id: 22,
        name: "Grace Williams",
        location: "Melbourne, Australia",
        coordinates: [144.9631, -37.8136],
        country: "Australia",
        specialization: "Gold Specimens",
        totalMinerals: 29,
        rareFinds: 8,
        yearsCollecting: 6,
        favoriteMineral: "Native Gold",
        bio: "Australian gold specimen collector from Victorian goldfields",
        profileImage: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=150&h=150&fit=crop&crop=face",
        minerals: ["Native Gold", "Quartz", "Pyrite", "Galena", "Sphalerite", "Chalcopyrite", "Tetrahedrite", "Scheelite"]
    },
    {
        id: 23,
        name: "Olaf Kristensen",
        location: "Copenhagen, Denmark",
        coordinates: [12.5683, 55.6761],
        country: "Denmark",
        specialization: "Greenland Minerals",
        totalMinerals: 42,
        rareFinds: 11,
        yearsCollecting: 13,
        favoriteMineral: "Tugtupite",
        bio: "Danish collector specializing in rare Greenlandic minerals",
        profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
        minerals: ["Tugtupite", "Sodalite", "Analcime", "Natrolite", "Ussingite", "Chkalovite", "Villiaumite", "Steenstrupine"]
    },
    {
        id: 24,
        name: "Priya Sharma",
        location: "Delhi, India",
        coordinates: [77.1025, 28.7041],
        country: "India",
        specialization: "Indian Gemstones",
        totalMinerals: 63,
        rareFinds: 15,
        yearsCollecting: 18,
        favoriteMineral: "Ruby",
        bio: "Indian gemstone collector specializing in corundum varieties",
        profileImage: "https://images.unsplash.com/photo-1581824485439-0312e2e2cd17?w=150&h=150&fit=crop&crop=face",
        minerals: ["Ruby", "Sapphire", "Spinel", "Garnet", "Tourmaline", "Beryl", "Chrysoberyl", "Zircon", "Moonstone", "Labradorite"]
    },
    {
        id: 25,
        name: "Franz Weber",
        location: "Vienna, Austria",
        coordinates: [16.3738, 48.2082],
        country: "Austria",
        specialization: "Austrian Classics",
        totalMinerals: 49,
        rareFinds: 10,
        yearsCollecting: 16,
        favoriteMineral: "Adularia",
        bio: "Austrian mineral collector from classic Alpine localities",
        profileImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
        minerals: ["Adularia", "Albite", "Epidote", "Actinolite", "Chlorite", "Titanite", "Rutile", "Hematite", "Pyrite"]
    },
    {
        id: 26,
        name: "Zara Al-Mansouri",
        location: "Doha, Qatar",
        coordinates: [51.5310, 25.2760],
        country: "Qatar",
        specialization: "Middle Eastern Minerals",
        totalMinerals: 31,
        rareFinds: 7,
        yearsCollecting: 8,
        favoriteMineral: "Celestite",
        bio: "Middle Eastern mineral collector focusing on regional specimens",
        profileImage: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=150&h=150&fit=crop&crop=face",
        minerals: ["Celestite", "Barite", "Gypsum", "Anhydrite", "Halite", "Calcite", "Dolomite", "Quartz"]
    },
    {
        id: 27,
        name: "Thomas Anderson",
        location: "Denver, Colorado",
        coordinates: [-104.9903, 39.7392],
        country: "United States",
        specialization: "Colorado Minerals",
        totalMinerals: 68,
        rareFinds: 17,
        yearsCollecting: 24,
        favoriteMineral: "Rhodochrosite",
        bio: "Colorado mineral specialist from the Rocky Mountain region",
        profileImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
        minerals: ["Rhodochrosite", "Fluorite", "Pyrite", "Galena", "Sphalerite", "Chalcopyrite", "Tetrahedrite", "Quartz", "Barite", "Calcite"]
    },
    {
        id: 28,
        name: "Lucia Bianchi",
        location: "Milan, Italy",
        coordinates: [9.1900, 45.4642],
        country: "Italy",
        specialization: "Alpine Minerals",
        totalMinerals: 54,
        rareFinds: 12,
        yearsCollecting: 17,
        favoriteMineral: "Diopside",
        bio: "Northern Italian Alpine mineral collector from Val d'Aosta",
        profileImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
        minerals: ["Diopside", "Vesuvianite", "Grossular", "Epidote", "Actinolite", "Titanite", "Adularia", "Albite", "Chlorite"]
    },
    {
        id: 29,
        name: "Pavel Novak",
        location: "Prague, Czech Republic",
        coordinates: [14.4378, 50.0755],
        country: "Czech Republic",
        specialization: "Bohemian Minerals",
        totalMinerals: 45,
        rareFinds: 9,
        yearsCollecting: 12,
        favoriteMineral: "Moldavite",
        bio: "Czech collector specializing in famous Bohemian mineral localities",
        profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
        minerals: ["Moldavite", "Garnet", "Fluorite", "Quartz", "Calcite", "Pyrite", "Galena", "Sphalerite", "Barite"]
    },
    {
        id: 30,
        name: "Elena Popovic",
        location: "Belgrade, Serbia",
        coordinates: [20.4489, 44.7866],
        country: "Serbia",
        specialization: "Balkan Minerals",
        totalMinerals: 40,
        rareFinds: 8,
        yearsCollecting: 10,
        favoriteMineral: "Realgar",
        bio: "Balkan mineral collector focusing on Serbian and regional specimens",
        profileImage: "https://images.unsplash.com/photo-1574701148212-8518049c7b0b?w=150&h=150&fit=crop&crop=face",
        minerals: ["Realgar", "Orpiment", "Pyrite", "Galena", "Sphalerite", "Chalcopyrite", "Quartz", "Calcite", "Barite"]
    }
];

// Personal collection data (simulating user's collection focus areas with detailed minerals)
const personalCollection = {
    focusAreas: [
        {
            name: "Washington State",
            state: "Washington",
            center: [-120.5, 47.5],
            intensity: 0.9,
            mineralCount: 23,
            description: "Primary collecting focus - Zeolites and Agates",
            minerals: [
                "Stilbite", "Heulandite", "Chabazite", "Laumontite", "Thomsonite",
                "Prehnite", "Apophyllite", "Calcite", "Agate", "Jasper",
                "Petrified Wood", "Thunder Eggs", "Chalcedony", "Carnelian",
                "Chrysoprase", "Bloodstone", "Moss Agate", "Plume Agate",
                "Dendritic Agate", "Blue Chalcedony", "Green Opal", "Wood Opal", "Fire Opal"
            ]
        },
        {
            name: "Colorado",
            state: "Colorado",
            center: [-105.5, 39.0],
            intensity: 0.7,
            mineralCount: 15,
            description: "Secondary focus - Rhodochrosite and Fluorite",
            minerals: [
                "Rhodochrosite", "Purple Fluorite", "Green Fluorite", "Clear Fluorite",
                "Pyrite", "Galena", "Sphalerite", "Chalcopyrite", "Tetrahedrite",
                "Quartz", "Smoky Quartz", "Amazonite", "Orthoclase", "Barite", "Calcite"
            ]
        },
        {
            name: "North Carolina",
            state: "North Carolina", 
            center: [-82.0, 35.5],
            intensity: 0.6,
            mineralCount: 12,
            description: "Gemstone collecting area - Emerald and Hiddenite",
            minerals: [
                "Emerald", "Hiddenite", "Kunzite", "Aquamarine", "Morganite",
                "Beryl", "Garnet", "Ruby", "Sapphire", "Moonstone",
                "Sunstone", "Quartz"
            ]
        },
        {
            name: "Arizona",
            state: "Arizona",
            center: [-111.5, 33.5],
            intensity: 0.5,
            mineralCount: 8,
            description: "Desert mineral collection - Turquoise and Chrysocolla",
            minerals: [
                "Turquoise", "Chrysocolla", "Azurite", "Malachite", "Cuprite",
                "Wulfenite", "Vanadinite", "Dioptase"
            ]
        }
    ],
    totalMinerals: 58,
    rareFinds: 12,
    yearsCollecting: 8
};

// Statistics
const globalStats = {
    totalCollectors: mineralCollectors.length,
    totalMinerals: mineralCollectors.reduce((sum, collector) => sum + collector.totalMinerals, 0),
    totalCountries: [...new Set(mineralCollectors.map(c => c.country))].length,
    averageMinerals: Math.round(mineralCollectors.reduce((sum, collector) => sum + collector.totalMinerals, 0) / mineralCollectors.length),
    topSpecializations: [
        "Quartz Varieties", "Alpine Minerals", "Gemstones", "Zeolites", "Fluorite"
    ]
};